coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
        branches: 
          - stable
          - dev
        if_ci_failed: error
        informational: false
        only_pulls: false
