build:
  environment:
    python: 3.10.9
  commands:
    coverage:
      file: '.coverge'
      config_file: '.coveragerc'
      # clover, cobertura, jacoco, python-cc, ruby-cc, go-cc, lcov
      format: 'python-cc'

  dependencies:
    before:
      - pip install -r requirements.txt


tools:
  external_code_coverage:
    runs: 2
