build:
  environment:
    python: pypy3.9-7.3.11
  nodes:
    coverage:
      tests:
        override:
          - command: 'make test'
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'

tools:
  external_code_coverage:
    runs: 2
