checks:
    python:
        code_rating: true
        duplicate_code: true
        typecheck_maybe_no_member: true
        classes_valid_slots: true
        basic_missing_reversed_argument: true
build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    -
                        command: 'py-scrutinizer-run command: pylint-run use_website_config: true'
                        use_website_config: true

        tests: true
filter:
    excluded_paths:
        - '*/tests/*'
    dependency_paths:
        - 'lib/*'
