build:
  dependencies:
    before:
      - pip install -r requirements.txt
  tests:
    override:
      - command: 'make test'
        coverage:
          file: '.coverage'
          config_file: '.coveragerc'
          format: 'py-cc'

