build:
  nodes:
    coverage:
      tests:
        override:
          checks:
            python:
              code_rating: true
              duplicate_code: true
  filter:
    paths: ["src/*", "tests/*"]
    environment:
      python: 3.6
      postgresql: false
      redis: false
      dependencies:
        override:
          - true
      tests:
        before:
          - pip install coverage
        override:
          - command: 'tox'
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'
      analysis:
        - py-scrutinizer-run
