from datetime import datetime
from io import TextIOWrapper
import logging

from .setup import get_date

def file_exists(files: str, mode: str) -> bool | None: ...
def last_updated() -> bool | datetime: ...
def load_logging_ini(config: str = ...): ...
def scan_dir(file: bool = ..., folders: bool = ...) -> list[str] | list[None]: ...
def get_project_folder() -> str: ...
def switch_root() -> str: ...
def create_package() -> None: ...
def get_package_name() -> TextIOWrapper | None: ...
def loc_package_file(
    name: str = ..., debug: bool = ..., mode: str = ...
) -> None | TextIOWrapper: ...

logger: logging.Logger

GREEN: str
RESET: str
MAGENTA: str
cwd: str
