from .setup import get_date as get_date
from _typeshed import Incomplete

def file_exists(file, mode): ...
def last_updated(): ...
def load_logging_ini(config: str = ...) -> None: ...
def scan_dir(files: bool = ..., folders: bool = ...): ...
def get_project_folder(): ...
def switch_root(): ...
def create_package() -> None: ...
def get_package_name(): ...
def loc_package_file(name=..., debug: bool = ..., mode: str = ...): ...

logger: Incomplete
GREEN: Incomplete
RESET: Incomplete
MAGENTA: Incomplete
cwd: Incomplete
