from _typeshed import Incomplete

class Courier:
    logger: Incomplete
    bashrc_path: Incomplete
    exists: Incomplete
    def __init__(self) -> None: ...
    @staticmethod
    def close_file(file) -> None: ...
    @staticmethod
    def get_file_path(): ...
    @staticmethod
    def assert_file_path(): ...
    @staticmethod
    def read_docs(file: str = ...): ...
    @staticmethod
    def print_formatted_list(lines) -> None: ...
    @staticmethod
    def proc_args(args, get_test: bool = ...) -> None: ...
    def get_package_created(self) -> None: ...
    @staticmethod
    def bashrc_exists(): ...
    def add_bashrc_alias(self) -> None: ...

courier: Incomplete
